# Generated by Django 2.1.4 on 2018-12-27 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceUnitRecord',
            fields=[
                ('id', models.BigIntegerField(help_text='主键', primary_key=True, serialize=False)),
                ('system_name', models.CharField(help_text='系统标识', max_length=64)),
                ('service_name', models.CharField(help_text='服务标识', max_length=64)),
                ('service_interface', models.CharField(help_text='服务接口标识', max_length=64)),
                ('total_num', models.IntegerField(help_text='调用总数')),
                ('slow_num', models.IntegerField(help_text='慢调用数')),
                ('slow_proportion', models.FloatField(help_text='慢调用占比')),
                ('fail_num', models.IntegerField(help_text='异常调用数')),
                ('fail_proportion', models.FloatField(help_text='异常调用占比')),
                ('avg_delay_sec', models.FloatField(help_text='平均耗时')),
                ('longest_delay_sec', models.FloatField(help_text='最长耗时')),
                ('shortest_delay_sec', models.FloatField(help_text='最短耗时')),
                ('strategy_id', models.IntegerField(default=1, help_text='统计策略id，默认1')),
                ('start_time', models.DateTimeField(auto_now_add=True, help_text='统计开始时间')),
                ('end_time', models.DateTimeField(auto_now_add=True, help_text='统计结束时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
            ],
        ),
        migrations.AlterField(
            model_name='testtable',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
